name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: nonprod-recebafacil
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '3.1.101'
  DIR_PORTAL: ./src/RecebaFacil.Portal
  DIR_TEST: ./src/RecebaFacil.Tests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup all the things
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: Build_n_Publish
        run: |
          dotnet restore RecebaFacil.Portal.csproj
          dotnet build RecebaFacil.Portal.csproj --configuration Release          
          dotnet publish RecebaFacil.Portal.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
        working-directory: ${{ env.DIR_PORTAL }}
      
      # Run Visual Studio Tests
      - name: Unit_Tests
        run: dotnet test RecebaFacil.Tests.csproj --verbosity minimal
        working-directory: ${{ env.DIR_TEST }}
          
      # Deploy to Azure Web apps
      - name: Deploy_to_Azure
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
