name: CI Master

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      dir_portal: ./src/RecebaFacil.Portal
      dir_tests: ./src/RecebaFacil.Tests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build RecebaFacil.Portal.csproj --configuration Release
      working-directory: ${{env.dir_portal}}
    - name: Test
      run: dotnet test RecebaFacil.Tests.csproj --verbosity quiet
      working-directory: ${{env.dir_tests}}
