name: CI showroom

on:
  push:
    branches: [ showroom ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      dir_portal: ./src/RecebaFacil.Portal
      dir_tests: ./src/RecebaFacil.Tests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.dir_portal}}
    - name: Build
      run: dotnet build RecebaFacil.Portal.csproj --configuration Release --no-restore
      working-directory: ${{env.dir_portal}}
    - name: Test
      run: dotnet test RecebaFacil.Tests.csproj --no-restore --verbosity minimal
      working-directory: ${{env.dir_tests}}
